// Todo: Create main CV elements in Divs

//--------------------------------------------------------------
//...............Arrays for holding all text....................
//--------------------------------------------------------------
const cvContent = [
  "Experience",
  "Education",
  "Certificates",
  "Skills",
  "Interests",
  "Profiles",
  "Contact"
]

const workExperience = [
  "<p>Embrace IT - Junior Software Engineer</p><p>We build IT stuff</p>",
  "<p>PMT Groep - Junior Consultant</p><p>Maak die pensioenkeuze nou gewoon</p>",
  "<p>CSV Ichthus Rotterdam - Treasurer</p><p>Ka ching</p>",
  "<p>Wybenga Advocaten - Legal Intern</p><p>I've got no idea what I'm doing, but I seem to be doing OK</p>"
]

const education = [
  "<p>Embrace IT - Web development traineeship</p><p></p>We build IT stuff",
  "<p>Erasmus University Rotterdam - LLM Health Law</p><p>Boy, I hope I'll actually be able to find a job</p>",
  "<p>Erasmus University Rotterdam - LLB Dutch Law</p><p>Wow, all these potential jobs look great!</p>"
]

const certificates = [
  "W3C HTML",
  "W3C CSS",
  "W3C Javascript",
  "Coursera HTML, CSS and JavaScript for Web Developers",
  "Coursera SQL",
  "Agile/Scrum",
  "Wft vermogen",
  "Wft inkomen",
  "Wft basis"
]

const madSkills = [
  "HTML5",
  "CSS3",
  "JavaScript",
  "Jquery",
  "Bootstrap",
  "TMap",
  "Agile/Scrum",
  "Git",
  "Jira"
]

const interests = [
  "Music and guitar",
  "Audio production",
  "Film",
  "Video Games"
]

const profiles = [
  "LinkedIn",
  "GitHub"
]

//--------------------------------------------------------------
//...............Behold all functions below.....................
//--------------------------------------------------------------

/* Functions for creating divs for content of CV with correct id
(respectively Work experience, skills etc and Embrace, PMT, Wybenga etc)*/
function createSections(){
const elements = []
  for (let section of cvContent){
    const sectionElement = document.createElement("div")
    const content = ""
    sectionElement.setAttribute("id", section)
    sectionElement.setAttribute("class", "section")
    elements.push(sectionElement)
  }
  return elements
}

function createSectionWorkExperience(jobNumberInArray){
  const newDiv = document.createElement("div")
  newDiv.innerHTML = workExperience[jobNumberInArray]
  return newDiv
}

function creatSubSection(numberInArray, arrayName){
  const newDiv = document.createElement("div")
  newDiv.innerHTML = arrayName[numberInArray]
  return newDiv
}

/* Function for inserting HTML generated by aforementioned functions into index.html*/
function insertSectionsIntoBodyCV(){

  //Insert main framework
  const elementsCV = createSections()
  const bodyCV = document.getElementById("bodyCV")
  for (let element of elementsCV){
    bodyCV.appendChild(element)
  }
  
  //Insert experience
  for (let i = 0, leng = workExperience.length; i < leng; i++){
    const xpDiv = document.getElementById("Experience")
    const experience = createSubSection(i,workExperience)
    xpDiv.appendChild(experience)
  }

  //Insert education
  for (let i = 0, leng = education.length; i < leng; i++){
    const eduDiv = document.getElementById("Education")
    const educationDiv = createSubSection(i,education)
    eduDiv.appendChild(educationDiv)
  }

  //Insert certificates
  for (let i = 0, leng = certificates.length; i < leng; i++){
    const certDiv = document.getElementById("Certificates")
    const certificate = createSubSection(i,certificates)
    eduDiv.appendChild(certificate)
  }

  //Insert mad skills

  //Insert interests

  //Insert Profiles

  //Insert contact
}


//Note to self: append content of each section after creation, so you can use getelementbyID